version: '3.8'

services:
  # Componente 1: Base de Datos No Relacional
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    command: mongod --bind_ip_all  
    volumes:
      - mongo_data:/data/db

  # Componente 2: Backend - Log de Eventos
  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/eventos

  # Componente 3: Frontend - Dashboard
  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000

volumes:
  mongo_data:
